### ISSUE TITLE
CCSE v. 2.021 - Stats menu crashes Game v2.031 (using Agronomicon)

### ISSUE THREAD

**Issue by Happyquack** [staticvariablejames/InsugarTrading#4]
Whenever I attempt to open the Stats menu, nothing within the menu loads past the background and the game appears to freeze. I can close and open this menu, as well as the Options and Info menu, with the game remaining frozen and nothing loading. I still see tooltips whenever I hover over objects. This is not always reproducible for me, and the more that I refresh the page the more that it seems to not happen.

**Comment by staticvariablejames** [comment]
The issue is with Agronomicon.

Agronomicon (which was not updated beyond Cookie Clicker v2.022) replaces `Game.UpdateMenu` with its own function, instead of rewriting its code. This is bound to cause conflicts with mods that rewrite `Game.UpdateMenu`, like CCSE.

It seems that loading Agronomicon after any code-rewriting mod fixes this issue.

Alternatively, Klattmose's [Horticookie](https://klattmose.github.io/CookieClicker/Horticookie.js) provides similar features as Agronomicon, you may try to use that instead.
